# Generated by Django 5.1 on 2026-04-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendor_email_alter_vendor_address'),
        ('invoice', '0003_invoice_customer_email_invoice_shipping_address'),
        ('store', '0003_item_low_stock_threshold_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
