# Generated by Django 5.1 on 2026-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_updated',
            field=models.BooleanField(default=False, help_text='True after stock has been incremented on marking as Received.'),
        ),
    ]
