# Generated by Django 5.1 on 2026-05-03 09:46

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vendor_options_vendor_company_name_and_more'),
        ('purchases', '0002_purchaseorder_stock_updated'),
        ('store', '0007_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=25, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='bill_number', unique=True)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bill', to='purchases.purchaseorder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to='accounts.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Bill',
                'verbose_name_plural': 'Purchase Bills',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost (₹)')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasebill')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bill_items', to='store.item')),
            ],
        ),
    ]
