# Generated by Django 5.1 on 2026-05-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasebill_purchasebillitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_bills', to='purchases.purchaseorder'),
        ),
    ]
