# Generated by Django 5.1 on 2026-04-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bills', '0001_initial'),
        ('store', '0003_item_low_stock_threshold_item_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Auto-generated BILL-YYYY-NNNN.', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='store.item'),
        ),
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax',
            field=models.FloatField(default=0, help_text='GST / input tax (₹)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(verbose_name='Total Amount Owing (₹)'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='institution_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_details',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
