# Generated by Django 5.1 on 2026-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_options_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address'),
        ),
    ]
